/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 3.18                       *
*        Compiled Jun 29 2011, 15:28:41                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ËÎÌו24.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 24                                            *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font24_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0021[ 17] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0022[ 12] = { /* code 0022, QUOTATION MARK */
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX__XX,________,
  _XX__XX_,________,
  _X___X__,________,
  X___X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0023[ 32] = { /* code 0023, NUMBER SIGN */
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  __X_____,X_______,
  __X_____,X_______,
  _X_____X,________,
  _X_____X,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0024[ 20] = { /* code 0024, DOLLAR SIGN */
  ____X___,
  ____X___,
  __XXXXX_,
  _XX_X_XX,
  XX__X_XX,
  XX__X_XX,
  XX__X___,
  _XX_X___,
  __XXX___,
  ___XXX__,
  ____XXX_,
  ____XXX_,
  ____X_XX,
  XX__X_XX,
  XX__X_XX,
  XX__X_XX,
  _X__X_X_,
  __XXXX__,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0025[ 32] = { /* code 0025, PERCENT SIGN */
  _XXX____,XX______,
  _X_X____,X_______,
  X___X___,X_______,
  X___X__X,________,
  X___X__X,________,
  X___X_XX,________,
  X___X_X_,________,
  _X_XXXXX,XX______,
  _XXX_X_X,_X______,
  _____XX_,__X_____,
  ____X_X_,__X_____,
  ____X_X_,__X_____,
  ___XX_X_,__X_____,
  ___X__X_,__X_____,
  ___X___X,_X______,
  __X____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0026[ 32] = { /* code 0026, AMPERSAND */
  ___XXX__,________,
  __X__XX_,________,
  __X__XX_,________,
  __X__XX_,________,
  __X__XX_,________,
  __X__X_X,XX______,
  __XXX___,X_______,
  __XX____,X_______,
  _X_XX___,X_______,
  _X__X__X,________,
  XX__XX_X,________,
  XX___XXX,________,
  XX___XX_,________,
  XX____XX,________,
  _XX__X_X,__X_____,
  __XXX___,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0027[  6] = { /* code 0027, APOSTROPHE */
  _XX_____,
  _XXX____,
  ___X____,
  ___X____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0028[ 21] = { /* code 0028, LEFT PARENTHESIS */
  _____X__,
  ____X___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  ___X____,
  ____X___,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0029[ 21] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __XX____,
  ___X____,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002A[ 24] = { /* code 002A, ASTERISK */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXX__X__,XXX_____,
  _XXX_X_X,XX______,
  ___XXXXX,________,
  ___XXXXX,________,
  _XXX_X_X,XX______,
  XXX__X__,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002B[ 22] = { /* code 002B, PLUS SIGN */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002C[  6] = { /* code 002C, COMMA */
  _XX_____,
  _XXX____,
  ___X____,
  ___X____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_002F[ 42] = { /* code 002F, SOLIDUS */
  ________,_X______,
  ________,XX______,
  ________,X_______,
  _______X,X_______,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____XX__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  ___X____,________,
  __X_____,________,
  __X_____,________,
  _XX_____,________,
  _X______,________,
  XX______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0030[ 32] = { /* code 0030, DIGIT ZERO */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0031[ 16] = { /* code 0031, DIGIT ONE */
  ____X___,
  ___XX___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0032[ 32] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _X____XX,________,
  X______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  ____X___,________,
  ___X____,________,
  __X_____,X_______,
  _X______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0033[ 32] = { /* code 0033, DIGIT THREE */
  __XXXX__,________,
  _X___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  ______XX,________,
  _____XX_,________,
  ___XXX__,________,
  ______XX,________,
  _______X,________,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X____XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0034[ 34] = { /* code 0034, DIGIT FOUR */
  _______X,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  ____X_XX,________,
  ___X__XX,________,
  ___X__XX,________,
  __X___XX,________,
  _X____XX,________,
  _X____XX,________,
  X_____XX,________,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0035[ 32] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X_XXXX_,________,
  _XX___XX,________,
  _X_____X,X_______,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_____XX,________,
  _X____XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0036[ 32] = { /* code 0036, DIGIT SIX */
  ____XXXX,________,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX_____,________,
  _X______,________,
  XX______,________,
  XX__XXXX,________,
  XX_X___X,X_______,
  XXX_____,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _X______,XX______,
  _XX_____,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0037[ 32] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,________,
  X_____X_,________,
  X_____X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0038[ 32] = { /* code 0038, DIGIT EIGHT */
  __XXXXXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX_____,X_______,
  _XXXX__X,X_______,
  ___XXXX_,________,
  _XX__XXX,________,
  _X_____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0039[ 32] = { /* code 0039, DIGIT NINE */
  ___XXXX_,________,
  _XX____X,________,
  _XX____X,X_______,
  XX______,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,XX______,
  _XX___X_,XX______,
  __XXXX__,XX______,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  _XX____X,________,
  _XX___XX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003A[ 12] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003B[ 13] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003C[ 34] = { /* code 003C, LESS-THAN SIGN */
  ________,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,________,
  __X_____,________,
  _X______,________,
  X_______,________,
  _X______,________,
  __X_____,________,
  ___X____,________,
  ____X___,________,
  _____X__,________,
  ______X_,________,
  _______X,________,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003D[ 12] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003E[ 34] = { /* code 003E, GREATER-THAN SIGN */
  X_______,________,
  _X______,________,
  __X_____,________,
  ___X____,________,
  ____X___,________,
  _____X__,________,
  ______X_,________,
  _______X,________,
  ________,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,________,
  __X_____,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_003F[ 34] = { /* code 003F, QUESTION MARK */
  ___XXXXX,________,
  _XX____X,X_______,
  X_______,XX______,
  X_______,XX______,
  XX______,XX______,
  XX______,XX______,
  _______X,X_______,
  ______XX,________,
  ____XX__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0040[ 32] = { /* code 0040, COMMERCIAL AT */
  ____XXXX,________,
  __XXX___,XX______,
  __X_____,_X______,
  _XX__XX_,X_X_____,
  _X__XX_X,X_X_____,
  XX__X__X,__X_____,
  XX__X__X,__X_____,
  XX_X___X,__X_____,
  XX_X___X,__X_____,
  XX_X__XX,__X_____,
  XX_X__XX,_X______,
  XX__XX_X,X_______,
  _XX_____,__X_____,
  _XX_____,_X______,
  __XX____,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0041[ 32] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  _____XX_,________,
  ____XXX_,________,
  ____X_XX,________,
  ____X_XX,________,
  ___X__XX,________,
  ___X___X,X_______,
  ___X___X,X_______,
  ___X___X,X_______,
  ___XXXXX,X_______,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,_XX_____,
  _XX_____,_XX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0042[ 32] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,________,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  _XXXXXXX,________,
  _XX_____,XX______,
  _XX_____,_X______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0043[ 32] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,XX______,
  __XX____,XX______,
  _XX_____,_X______,
  _XX_____,_X______,
  _X______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,_X______,
  _XX_____,_X______,
  _XX_____,X_______,
  __XX___X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0044[ 32] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX___XX,X_______,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0045[ 32] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XX______,
  _XX_____,_X______,
  _XX_____,__X_____,
  _XX_____,________,
  _XX_____,________,
  _XX____X,________,
  _XX____X,________,
  _XXXXXXX,________,
  _XX____X,________,
  _XX____X,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,_X______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0046[ 32] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XX______,
  _XX_____,XX______,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,________,
  _XX____X,________,
  _XX____X,________,
  _XXXXXXX,________,
  _XX____X,________,
  _XX____X,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0047[ 32] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXX_,X_______,
  __XX___X,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _X______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX___XXX,XXX_____,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0048[ 32] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX____,XXXX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004A[ 38] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XXXXX,XXX_____,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XX____XX,________,
  XX___XX_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004B[ 32] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXX__XX,XXX_____,
  _XX_____,X_______,
  _XX____X,________,
  _XX___X_,________,
  _XX___X_,________,
  _XX__X__,________,
  _XX_XX__,________,
  _XXXXX__,________,
  _XXX_XX_,________,
  _XX__XXX,________,
  _XX___XX,________,
  _XX___XX,X_______,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XXX_____,
  XXXX___X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004C[ 32] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,_X______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004D[ 32] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _X_XX__X,_XX_____,
  _X_XX__X,_XX_____,
  _X_XX__X,_XX_____,
  _X_XX__X,_XX_____,
  _X_XX_X_,_XX_____,
  _X__XXX_,_XX_____,
  _X__XXX_,_XX_____,
  _X__XXX_,_XX_____,
  _X__XXX_,_XX_____,
  _X___X__,_XX_____,
  _X___X__,_XX_____,
  XXX__X__,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004E[ 32] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,_XXX____,
  _XXX____,__X_____,
  _XXX____,__X_____,
  _X_XX___,__X_____,
  _X_XX___,__X_____,
  _X__XX__,__X_____,
  _X___XX_,__X_____,
  _X___XX_,__X_____,
  _X____XX,__X_____,
  _X____XX,__X_____,
  _X_____X,X_X_____,
  _X______,XXX_____,
  _X______,XXX_____,
  _X______,_XX_____,
  _X______,_XX_____,
  XXX_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_004F[ 32] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX_____,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0050[ 32] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,X_______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  _XXXXXXX,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0051[ 36] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX_____,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_XXX__,XX______,
  _XX__X__,X_______,
  _XX___XX,X_______,
  __X___XX,________,
  ___XXXXX,________,
  ______XX,XX______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0052[ 32] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,X_______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  _XXXXXXX,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  XXXX____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0053[ 32] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,_X______,
  _XX____X,XX______,
  XX______,_X______,
  XX______,_X______,
  XX______,________,
  XXX_____,________,
  _XXXX___,________,
  ___XXXX_,________,
  _____XXX,X_______,
  _______X,X_______,
  ________,XX______,
  X_______,XX______,
  X_______,XX______,
  XX______,XX______,
  XXX____X,X_______,
  X__XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0054[ 32] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,XXX_____,
  _X___XX_,__X_____,
  X____XX_,___X____,
  X____XX_,___X____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0055[ 32] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX____,_XXX____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  __XX____,_X______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0056[ 32] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXXX___,XXXX____,
  _XXX____,_XX_____,
  __XX____,_X______,
  __XX____,_X______,
  __XX____,_X______,
  __XX____,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ____XX_X,________,
  ____XX_X,________,
  ____XX_X,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0057[ 32] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX_XXX,_XXX____,
  _XX__XX_,__X_____,
  _XX__XX_,__X_____,
  _XX__XX_,_X______,
  _XX__XX_,_X______,
  _XX__XXX,_X______,
  __XX_XXX,_X______,
  __XX_XXX,_X______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX__X,X_______,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0058[ 32] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX__XX,XX______,
  _XX____X,X_______,
  __XX___X,________,
  __XX___X,________,
  __XX__X_,________,
  ___XX_X_,________,
  ___XXX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XXX_,________,
  ___X_XX_,________,
  ___X_XXX,________,
  __XX__XX,________,
  __X___XX,________,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0059[ 32] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXX___,XXXX____,
  _XXX____,_XX_____,
  __XX____,_X______,
  __XX____,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ____XX_X,________,
  ____XX_X,________,
  ____XXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005A[ 32] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XX______,
  _X_____X,X_______,
  X_____XX,X_______,
  ______XX,________,
  _____XXX,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,_X______,
  _XXX____,_X______,
  _XX_____,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005B[ 21] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXXXX__,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005C[ 40] = { /* code 005C, REVERSE SOLIDUS */
  X_______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  __X_____,________,
  __X_____,________,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  ____X___,________,
  ____X___,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ______X_,________,
  ______X_,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005D[ 21] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXXXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005E[  3] = { /* code 005E, CIRCUMFLEX ACCENT */
  __XXX___,
  _XX_XX__,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Font24_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0060[  2] = { /* code 0060, GRAVE ACCENT */
  _XX_____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0061[ 22] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  ____XXXX,X_______,
  __XXX__X,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_X_____,
  _XXXXX_X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0062[ 34] = { /* code 0062, LATIN SMALL LETTER B */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,________,
  _XXXX__X,X_______,
  _XXX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,X_______,
  _XXX___X,X_______,
  _X_XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0063[ 22] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XX____XX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,X_______,
  _XX_____,X_______,
  _XX____X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0064[ 34] = { /* code 0064, LATIN SMALL LETTER D */
  ________,X_______,
  ______XX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,XX______,
  __XXXX_X,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0065[ 22] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXX_,________,
  _XX___XX,________,
  _X_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  _XX_____,X_______,
  _XXX___X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0066[ 32] = { /* code 0066, LATIN SMALL LETTER F */
  _____XXX,X_______,
  ____XX__,XX______,
  ___XX___,XX______,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,X_______,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0067[ 28] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXXX_,XXX_____,
  __XX__XX,__X_____,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  __XXXXX_,________,
  _XX_____,________,
  _XXXXX__,________,
  __XXXXXX,X_______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0068[ 34] = { /* code 0068, LATIN SMALL LETTER H */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_XXXX,________,
  _XXX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006A[ 19] = { /* code 006A, LATIN SMALL LETTER J */
  _____XX_,
  _____XX_,
  ________,
  ________,
  ________,
  __XXXXX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006B[ 34] = { /* code 006B, LATIN SMALL LETTER K */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,X_______,
  _XX___X_,________,
  _XX__XX_,________,
  _XX__X__,________,
  _XX_XX__,________,
  _XXXXX__,________,
  _XXX_XX_,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006C[ 17] = { /* code 006C, LATIN SMALL LETTER L */
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006D[ 22] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XXX_,XXX_____,
  _XXX_XXX,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  XXXX_XXX,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006E[ 22] = { /* code 006E, LATIN SMALL LETTER N */
  XXX__XXX,________,
  _XXXX__X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_006F[ 22] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0070[ 28] = { /* code 0070, LATIN SMALL LETTER P */
  XXX_XXXX,________,
  _XXX___X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  _XXX___X,X_______,
  _XX_XXXX,________,
  _XX_____,________,
  _XX_____,________,
  XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0071[ 28] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXX__,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0072[ 22] = { /* code 0072, LATIN SMALL LETTER R */
  XXXXX__X,XXX_____,
  ___XX_X_,_XX_____,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0073[ 22] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXXX,X_______,
  _XX____X,X_______,
  XX______,X_______,
  XX______,________,
  _XXX____,________,
  __XXXXX_,________,
  _____XXX,________,
  X______X,X_______,
  X______X,X_______,
  XX____XX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0074[ 30] = { /* code 0074, LATIN SMALL LETTER T */
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,X_______,
  ___XX___,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0075[ 24] = { /* code 0075, LATIN SMALL LETTER U */
  __X_____,X_______,
  XXX___XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX__XX,XX______,
  __XXXX_X,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0076[ 22] = { /* code 0076, LATIN SMALL LETTER V */
  XXXXX__X,XXX_____,
  _XXX____,XX______,
  __XX____,X_______,
  __XX____,X_______,
  ___XX__X,________,
  ___XX__X,________,
  ___XX__X,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0077[ 22] = { /* code 0077, LATIN SMALL LETTER W */
  XXXX_XXX,X_XX____,
  _XX___XX,__X_____,
  _XX___XX,__X_____,
  _XX__XXX,__X_____,
  __XX_XXX,__X_____,
  __XX_X_X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  ___X____,X_______,
  ___X____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0078[ 22] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXX_XX,XX______,
  __XX___X,________,
  __XX__XX,________,
  ___XX_X_,________,
  ___XXX__,________,
  ____XX__,________,
  ____XXX_,________,
  ___X_XX_,________,
  __XX__XX,________,
  __X___XX,X_______,
  XXXX_XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_0079[ 28] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXXX_XX,XX______,
  _XXX___X,________,
  __XX___X,________,
  __XX___X,________,
  ___XX_X_,________,
  ___XX_X_,________,
  ___XX_X_,________,
  ____XX__,________,
  ____XX__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  _X_X____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007A[ 22] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,________,
  X____XX_,________,
  X___XXX_,________,
  ____XX__,________,
  ___XXX__,________,
  ___XX___,________,
  __XXX___,________,
  __XX____,X_______,
  _XXX____,X_______,
  _XX____X,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007B[ 21] = { /* code 007B, LEFT CURLY BRACKET */
  ___XX___,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  X_______,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007C[ 24] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007D[ 21] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __XX____,
  ____X___,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007E[ 10] = { /* code 007E, TILDE */
  _XXX____,________,
  _X__X___,________,
  X____X__,__X_____,
  X_____X_,_X______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font24_007F[  1] = { /* code 007F, <control> */
  ________};


/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font24_4E00[  6] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,___XX___,
  _XXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E01[ 63] = { /* code 4E01 */
  ________,________,________,
  ________,________,___XX___,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  _______X,XXXX____,________,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E02[ 63] = { /* code 4E02 */
  ________,________,___X____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,________,________,
  _______X,________,________,
  ______XX,________,________,
  ______X_,________,________,
  _____XX_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ________,________,_X______,
  ________,________,XX______,
  ________,________,XX______,
  ________,________,XX______,
  ________,________,XX______,
  ________,________,X_______,
  ________,________,X_______,
  ________,_______X,X_______,
  ________,_XXX___X,X_______,
  ________,___XXXXX,________,
  ________,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E03[ 63] = { /* code 4E03 */
  ________,________,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,___X____,
  ________,_XX_____,__XXX___,
  ________,_XX____X,XX______,
  ________,_XXXXXX_,________,
  _______X,XXX_____,________,
  ___XXXX_,_XX_____,________,
  XXX_____,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,____X___,
  ________,_XX_____,____X___,
  ________,_XX_____,____X___,
  ________,_XX_____,____X___,
  ________,_XX_____,____XX__,
  ________,__XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E04[ 60] = { /* code 4E04 */
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,___XX___,
  _XXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E05[ 63] = { /* code 4E05 */
  ________,________,___X____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E06[ 45] = { /* code 4E06 */
  ________,________,___X____,
  ________,________,__XXX___,
  __XXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_X______,________,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,________,
  _______X,________,________,
  ______X_,________,________,
  ____XX__,________,________,
  ___XX___,________,________,
  _XX_____,________,________,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_4E07[ 63] = { /* code 4E07 */
  ________,________,________,
  ________,________,___XX___,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,_X______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,_X______,
  ________,XXXXXXXX,XXX_____,
  ________,XX______,XX______,
  ________,XX______,XX______,
  ________,X_______,XX______,
  ________,X_______,XX______,
  _______X,X_______,XX______,
  _______X,________,XX______,
  ______XX,________,X_______,
  ______X_,________,X_______,
  _____XX_,________,X_______,
  ____XX__,_______X,X_______,
  ___XX___,___XX__X,X_______,
  __XX____,_____XXX,________,
  _X______,_____XX_,________};



GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Font24_CharInfo[22059] = {
   {   1,   1,   0,  21,  12, acGUI_Font24_0020 } /* code 0020, SPACE */
  ,{   3,  17,   5,   4,  12, acGUI_Font24_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   9,   6,   2,   2,  12, acGUI_Font24_0022 } /* code 0022, QUOTATION MARK */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0023 } /* code 0023, NUMBER SIGN */
  ,{   8,  20,   2,   3,  12, acGUI_Font24_0024 } /* code 0024, DOLLAR SIGN */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0025 } /* code 0025, PERCENT SIGN */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0026 } /* code 0026, AMPERSAND */
  ,{   4,   6,   1,   2,  12, acGUI_Font24_0027 } /* code 0027, APOSTROPHE */
  ,{   6,  21,   5,   2,  12, acGUI_Font24_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   6,  21,   1,   2,  12, acGUI_Font24_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{  11,  12,   1,   6,  12, acGUI_Font24_002A } /* code 002A, ASTERISK */
  ,{  11,  11,   1,   7,  12, acGUI_Font24_002B } /* code 002B, PLUS SIGN */
  ,{   4,   6,   1,  18,  12, acGUI_Font24_002C } /* code 002C, COMMA */
  ,{  10,   1,   1,  12,  12, acGUI_Font24_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   3,   2,  18,  12, acGUI_Font24_002E } /* code 002E, FULL STOP */
  ,{  10,  21,   1,   2,  12, acGUI_Font24_002F } /* code 002F, SOLIDUS */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  16,   2,   5,  12, acGUI_Font24_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  16,   1,   5,  12, acGUI_Font24_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  16,   1,   5,  12, acGUI_Font24_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  16,   1,   5,  12, acGUI_Font24_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  16,   2,   5,  12, acGUI_Font24_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  12,   5,   9,  12, acGUI_Font24_003A } /* code 003A, COLON */
  ,{   2,  13,   5,  10,  12, acGUI_Font24_003B } /* code 003B, SEMICOLON */
  ,{   9,  17,   2,   4,  12, acGUI_Font24_003C } /* code 003C, LESS-THAN SIGN */
  ,{  10,   6,   1,  10,  12, acGUI_Font24_003D } /* code 003D, EQUALS SIGN */
  ,{   9,  17,   2,   4,  12, acGUI_Font24_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_003F } /* code 003F, QUESTION MARK */
  ,{  11,  16,   1,   5,  12, acGUI_Font24_0040 } /* code 0040, COMMERCIAL AT */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  16,   1,   5,  12, acGUI_Font24_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   8,  16,   2,   5,  12, acGUI_Font24_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  11,  19,   1,   5,  12, acGUI_Font24_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  11,  16,   0,   5,  12, acGUI_Font24_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  18,   1,   5,  12, acGUI_Font24_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  12,  16,   0,   5,  12, acGUI_Font24_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   6,  21,   5,   2,  12, acGUI_Font24_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   9,  20,   2,   4,  12, acGUI_Font24_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   6,  21,   2,   2,  12, acGUI_Font24_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   7,   3,   3,   2,  12, acGUI_Font24_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{  12,   1,   0,  23,  12, acGUI_Font24_005F } /* code 005F, LOW LINE */
  ,{   5,   2,   2,   2,  12, acGUI_Font24_0060 } /* code 0060, GRAVE ACCENT */
  ,{  11,  11,   1,  10,  12, acGUI_Font24_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  11,   1,  10,  12, acGUI_Font24_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   9,  11,   2,  10,  12, acGUI_Font24_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  10,  16,   1,   5,  12, acGUI_Font24_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  11,  14,   1,  10,  12, acGUI_Font24_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   8,  16,   2,   5,  12, acGUI_Font24_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   7,  19,   2,   5,  12, acGUI_Font24_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  17,   1,   4,  12, acGUI_Font24_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   8,  17,   2,   4,  12, acGUI_Font24_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  12,  11,   0,  10,  12, acGUI_Font24_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  10,  11,   1,  10,  12, acGUI_Font24_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  10,  11,   1,  10,  12, acGUI_Font24_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  10,  14,   1,  10,  12, acGUI_Font24_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  10,  14,   1,  10,  12, acGUI_Font24_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  11,  11,   0,  10,  12, acGUI_Font24_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   9,  11,   2,  10,  12, acGUI_Font24_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   9,  15,   1,   6,  12, acGUI_Font24_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  10,  12,   1,   9,  12, acGUI_Font24_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  11,  11,   1,  10,  12, acGUI_Font24_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  12,  11,   0,  10,  12, acGUI_Font24_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  10,  11,   1,  10,  12, acGUI_Font24_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  10,  14,   1,  10,  12, acGUI_Font24_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   9,  11,   2,  10,  12, acGUI_Font24_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,  21,   5,   2,  12, acGUI_Font24_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  24,   6,   0,  12, acGUI_Font24_007C } /* code 007C, VERTICAL LINE */
  ,{   5,  21,   2,   2,  12, acGUI_Font24_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{  11,   5,   1,   1,  12, acGUI_Font24_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  21,  12, acGUI_Font24_007F } /* code 007F, <control> */
  ,{  22,   2,   1,  10,  24, acGUI_Font24_4E00 } /* code 4E00, <CJK Ideograph, First> */
  ,{  22,  21,   1,   2,  24, acGUI_Font24_4E01 } /* code 4E01 */
  ,{  22,  21,   1,   2,  24, acGUI_Font24_4E02 } /* code 4E02 */
  ,{  22,  21,   1,   1,  24, acGUI_Font24_4E03 } /* code 4E03 */
  ,{  22,  20,   1,   2,  24, acGUI_Font24_4E04 } /* code 4E04 */
  ,{  22,  21,   1,   2,  24, acGUI_Font24_4E05 } /* code 4E05 */
  ,{  22,  15,   1,   3,  24, acGUI_Font24_4E06 } /* code 4E06 */
  ,{  22,  21,   1,   2,  24, acGUI_Font24_4E07 } /* code 4E07 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font24_Prop2 = {
   0x4E00 /* first character */
  ,0x4E07 /* last character  */
  ,&GUI_Font24_CharInfo[96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font24_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Font24_CharInfo[  0] /* address of first character */
  ,&GUI_Font24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

